# Generated by Django 2.2.4 on 2019-09-13 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='programa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='programas.Programa'),
            preserve_default=False,
        ),
    ]
