# Generated by Django 2.2.4 on 2019-09-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descritivo', models.TextField(max_length=1000)),
                ('data', models.DateField()),
            ],
        ),
    ]
