# Generated by Django 2.2.4 on 2019-09-16 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0001_initial'),
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='programas.Programa'),
        ),
    ]
