# Generated by Django 2.2.4 on 2019-09-16 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20190911_1402'),
        ('diario', '0003_diario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diario',
            name='user',
        ),
        migrations.AddField(
            model_name='diario',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.Usuario'),
            preserve_default=False,
        ),
    ]
