# Generated by Django 2.2.4 on 2019-09-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0004_auto_20190916_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='lida',
            field=models.BooleanField(default='False'),
        ),
    ]
