# Generated by Django 2.2.4 on 2019-09-11 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20190911_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='programas.Programa'),
        ),
    ]
