# Generated by Django 2.2.4 on 2019-09-11 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_proprietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.Usuario'),
            preserve_default=False,
        ),
    ]
